### ISSUE TITLE
Running goczmq tests / benchmarks SIGABRT

### ISSUE THREAD

**Issue by vrecan** [zeromq/goczmq#136]
OS: centos 7
x86_64
zmq 4.0.5
czmq 3.0.2
libsodium 1.0.3
```
  goczmq git:(master) go test -bench=.  
goczmq.test: src/zsockopt.c:482: zsocket_set_curve_secretkey_bin: Assertion `rc == 0 || zmq_errno () == (156384712 + 53)' failed.
SIGABRT: abort
PC=0x7f4af4ce15d7
signal arrived during cgo execution

goroutine 7 [syscall, locked to thread]:
runtime.cgocall_errno(0x406340, 0xc208018e20, 0x0)
	/usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208018e00 sp=0xc208018dd8
github.com/zeromq/goczmq._Cfunc_zsocket_set_curve_secretkey_bin(0xdd1120, 0xdd2060)
	github.com/zeromq/goczmq/_test/_obj_test/_cgo_gotypes.go:919 +0x45 fp=0xc208018e20 sp=0xc208018e00
github.com/zeromq/goczmq.(*Cert).Apply(0xc20804e098, 0xc20803b800)
	/home/vrecan/go/src/github.com/zeromq/goczmq/cert.go:76 +0x5e fp=0xc208018e40 sp=0xc208018e20
github.com/zeromq/goczmq.TestAuthCurveAllow(0xc20806e120)
	/home/vrecan/go/src/github.com/zeromq/goczmq/auth_test.go:224 +0x23c fp=0xc208018f78 sp=0xc208018e40
testing.tRunner(0xc20806e120, 0x8b07b0)
	/usr/local/go/src/testing/testing.go:447 +0xbf fp=0xc208018fd0 sp=0xc208018f78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fd8 sp=0xc208018fd0
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x624820, 0x8b0780, 0x45, 0x45, 0x8c4c01)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208050460, 0x8af8c0)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/zeromq/goczmq/_test/_testmain.go:228 +0x1d5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

rax     0x0
rbx     0x7f4af5bf0000
rcx     0xffffffffffffffff
rdx     0x6
rdi     0x6814
rsi     0x6814
rbp     0x7f4af4e2a128
rsp     0x7fff264b1da8
r8      0x1
r9      0xfefefefffeff092d
r10     0x8
r11     0x206
r12     0x7f4af57b2848
r13     0x7f4af57c22e0
r14     0x2
r15     0xc20803c780
rip     0x7f4af4ce15d7
rflags  0x206
cs      0x33
fs      0x0
gs      0x0
exit status 2
```

**Comment by vrecan** [comment]
go test -v results
```
go test -v
=== RUN TestAuthIPAllow
I: 15-06-11 15:23:39 zauth: API command=ALLOW
I: 15-06-11 15:23:39 zauth: - whitelisting ipaddress=127.0.0.1
I: 15-06-11 15:23:39 zauth: ZAP request mechanism=NULL ipaddress=127.0.0.1
I: 15-06-11 15:23:39 zauth: - passed (whitelist) address=127.0.0.1
I: 15-06-11 15:23:39 zauth: - ZAP reply status_code=200 status_text=OK
I: 15-06-11 15:23:39 zauth: API command=$TERM
--- PASS: TestAuthIPAllow (0.00s)
=== RUN TestAuthPlain
I: 15-06-11 15:23:39 zauth: API command=ALLOW
I: 15-06-11 15:23:39 zauth: - whitelisting ipaddress=127.0.0.1
I: 15-06-11 15:23:39 zauth: API command=PLAIN
I: 15-06-11 15:23:39 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
I: 15-06-11 15:23:39 zauth: - passed (whitelist) address=127.0.0.1
I: 15-06-11 15:23:39 zauth: - allowed (PLAIN) username=admin password=Password
I: 15-06-11 15:23:39 zauth: - ZAP reply status_code=200 status_text=OK
I: 15-06-11 15:23:39 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
I: 15-06-11 15:23:39 zauth: - passed (whitelist) address=127.0.0.1
I: 15-06-11 15:23:39 zauth: - denied (PLAIN) username=admin password=BadPassword
I: 15-06-11 15:23:39 zauth: - ZAP reply status_code=400 status_text=No access
I: 15-06-11 15:23:39 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
I: 15-06-11 15:23:39 zauth: - passed (whitelist) address=127.0.0.1
I: 15-06-11 15:23:39 zauth: - denied (PLAIN) username=admin password=BadPassword
I: 15-06-11 15:23:39 zauth: - ZAP reply status_code=400 status_text=No access
I: 15-06-11 15:23:39 zauth: API command=$TERM
--- PASS: TestAuthPlain (0.20s)
=== RUN TestAuthCurveAllow
goczmq.test: src/zsockopt.c:482: zsocket_set_curve_secretkey_bin: Assertion `rc == 0 || zmq_errno () == (156384712 + 53)' failed.
SIGABRT: abort
PC=0x7fceba1d65d7
signal arrived during cgo execution

goroutine 7 [syscall, locked to thread]:
runtime.cgocall_errno(0x406340, 0xc208018e20, 0x0)
	/usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208018e00 sp=0xc208018dd8
github.com/zeromq/goczmq._Cfunc_zsocket_set_curve_secretkey_bin(0xb619a0, 0xb66250)
	github.com/zeromq/goczmq/_test/_obj_test/_cgo_gotypes.go:919 +0x45 fp=0xc208018e20 sp=0xc208018e00
github.com/zeromq/goczmq.(*Cert).Apply(0xc20804e098, 0xc20803b840)
	/home/vrecan/go/src/github.com/zeromq/goczmq/cert.go:76 +0x5e fp=0xc208018e40 sp=0xc208018e20
github.com/zeromq/goczmq.TestAuthCurveAllow(0xc20806e120)
	/home/vrecan/go/src/github.com/zeromq/goczmq/auth_test.go:224 +0x23c fp=0xc208018f78 sp=0xc208018e40
testing.tRunner(0xc20806e120, 0x8b07b0)
	/usr/local/go/src/testing/testing.go:447 +0xbf fp=0xc208018fd0 sp=0xc208018f78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fd8 sp=0xc208018fd0
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x624820, 0x8b0780, 0x45, 0x45, 0x8c4c01)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208050460, 0x8af8c0)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/zeromq/goczmq/_test/_testmain.go:228 +0x1d5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

rax     0x0
rbx     0x7fcebb0e4000
rcx     0xffffffffffffffff
rdx     0x6
rdi     0x6a9f
rsi     0x6a9f
rbp     0x7fceba31f128
rsp     0x7fff534c30c8
r8      0x1
r9      0xfefefefefeff092d
r10     0x8
r11     0x206
r12     0x7fcebaca7848
r13     0x7fcebacb72e0
r14     0x2
r15     0xc20803c780
rip     0x7fceba1d65d7
rflags  0x206
cs      0x33
fs      0x0
gs      0x0
exit status 2
FAIL	github.com/zeromq/goczmq	0.208s
```

**Comment by vrecan** [comment]
I was linking to a version of zermq without libsodium. When I reinstalled zmq 4.0.5 it started working!

**Comment by PSG-Luna** [comment]
@taotetek Do we want to support builds without libsodium ? If so we'll need to do some magic with headers
