### ISSUE TITLE
Channels test fail on windows

### ISSUE THREAD

**Issue by vrecan** [zeromq/goczmq#139]
I commented out all other tests to narrow down which tests were failing. Here is the output

```
$ go test -v
=== RUN TestDealerRouterChanneler
--- PASS: TestDealerRouterChanneler (0.01s)
=== RUN: ExampleChanneler_output
--- PASS: ExampleChanneler_output (0.01s)
PASS
E: 15-06-14 00:53:42 dangling 'PUSH' socket created at C:/Users/ben.aldrich/go/src/github.com/zeromq/goczmq/sock.go:184
Assertion failed: Successful WSASTARTUP not yet performed (signaler.cpp:183)
Exception 0x40000015 0x697bc8a0 0x7fefe212ae0 0x7fefd7d940d
PC=0x7fefd7d940d
signal arrived during cgo execution

syscall.ExitProcess(0xc000000000)
        c:/go/src/syscall/zsyscall_windows.go:260 +0x63
syscall.Exit(0x0)
        c:/go/src/syscall/syscall_windows.go:227 +0x30
os.Exit(0x0)
        c:/go/src/os/proc.go:49 +0x2f
main.main()
        github.com/zeromq/goczmq/_test/_testmain.go:56 +0x1ea

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [runnable, locked to thread]:
github.com/zeromq/goczmq._Cfunc_zsock_destroy_checked(0xc082004ec0, 0x758a60, 0xdb)
        github.com/zeromq/goczmq/_test/_obj_test/_cgo_gotypes.go:379 +0x4c
github.com/zeromq/goczmq.(*Sock).Destroy(0xc082004ec0)
        C:/Users/ben.aldrich/go/src/github.com/zeromq/goczmq/sock.go:410 +0x68
github.com/zeromq/goczmq.(*Channeler).channeler(0xc082010230, 0xc0820426c0, 0xc082042720)
        C:/Users/ben.aldrich/go/src/github.com/zeromq/goczmq/channeler.go:163 +0x425
created by github.com/zeromq/goczmq.newChanneler
        C:/Users/ben.aldrich/go/src/github.com/zeromq/goczmq/channeler.go:185 +0x43e
rax     0x604acdc6
rbx     0x697bc8a0
rcx     0x28bf2f0
rdx     0xb0
rdi     0x6fb1da40
rsi     0x7fefe193fc0
rbp     0x28bfb60
rsp     0x28bf900
r8      0x0
r9      0x0
r10     0x0
r11     0x28bf940
r12     0x6fb1da30
r13     0x6fb1da38
r14     0x77657be0
r15     0x77652670
rip     0x7fefd7d940d
rflags  0x7fe00000206
cs      0x33
fs      0x53
gs      0x2b
exit status 2
FAIL    github.com/zeromq/goczmq        0.280s
```

This is on windows 7 with:
zeromq 4.0.5
czmq 3.0.1
libsodium 1.0.3

**Comment by vrecan** [comment]
Failure in auth as well:

```
$ go test -v
=== RUN TestAuthIPAllow
I: 15-06-14 00:58:43 zauth: API command=ALLOW
I: 15-06-14 00:58:43 zauth: - whitelisting ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: ZAP request mechanism=NULL ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: - passed (whitelist) address=127.0.0.1
I: 15-06-14 00:58:43 zauth: - ZAP reply status_code=200 status_text=OK
I: 15-06-14 00:58:43 zauth: API command=$TERM
--- PASS: TestAuthIPAllow (0.01s)
=== RUN TestAuthPlain
I: 15-06-14 00:58:43 zauth: API command=ALLOW
I: 15-06-14 00:58:43 zauth: - whitelisting ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: API command=PLAIN
I: 15-06-14 00:58:43 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: - passed (whitelist) address=127.0.0.1
I: 15-06-14 00:58:43 zauth: - allowed (PLAIN) username=admin password=Password
I: 15-06-14 00:58:43 zauth: - ZAP reply status_code=200 status_text=OK
I: 15-06-14 00:58:43 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: - passed (whitelist) address=127.0.0.1
I: 15-06-14 00:58:43 zauth: - denied (PLAIN) username=admin password=BadPassword
I: 15-06-14 00:58:43 zauth: - ZAP reply status_code=400 status_text=No access
I: 15-06-14 00:58:43 zauth: API command=$TERM
--- PASS: TestAuthPlain (0.20s)
=== RUN TestAuthCurveAllow
I: 15-06-14 00:58:43 zauth: API command=CURVE
I: 15-06-14 00:58:43 zauth: ZAP request mechanism=CURVE ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: - allowed (CURVE allow any client)
I: 15-06-14 00:58:43 zauth: - ZAP reply status_code=200 status_text=OK
I: 15-06-14 00:58:43 zauth: API command=$TERM
--- PASS: TestAuthCurveAllow (0.21s)
=== RUN TestAuthCurveCertificate
I: 15-06-14 00:58:43 zauth: API command=CURVE
I: 15-06-14 00:58:43 zauth: ZAP request mechanism=CURVE ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: - allowed (CURVE) client_key=?lv3e!ST(gub>hh&{Pu6d$1TciQMARcM<r4}cFz3
I: 15-06-14 00:58:43 zauth: - ZAP reply status_code=200 status_text=OK
I: 15-06-14 00:58:43 zauth: ZAP request mechanism=CURVE ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: - denied (CURVE) client_key=s6tPza%VS(D0(%c/t%Y9bB2rP*tgpXzIR[IfM<Nc
I: 15-06-14 00:58:43 zauth: - ZAP reply status_code=400 status_text=No access
I: 15-06-14 00:58:43 zauth: ZAP request mechanism=CURVE ipaddress=127.0.0.1
I: 15-06-14 00:58:43 zauth: - denied (CURVE) client_key=s6tPza%VS(D0(%c/t%Y9bB2rP*tgpXzIR[IfM<Nc
I: 15-06-14 00:58:43 zauth: - ZAP reply status_code=400 status_text=No access
I: 15-06-14 00:58:43 zauth: API command=$TERM
--- PASS: TestAuthCurveCertificate (0.21s)
PASS
Assertion failed: Successful WSASTARTUP not yet performed (signaler.cpp:183)
Exception 0x40000015 0x697bc8a0 0x7fefe212ae0 0x7fefd7d940d
PC=0x7fefd7d940d
signal arrived during cgo execution

syscall.ExitProcess(0xc000000000)
        c:/go/src/syscall/zsyscall_windows.go:260 +0x63
syscall.Exit(0x0)
        c:/go/src/syscall/syscall_windows.go:227 +0x30
os.Exit(0x0)
        c:/go/src/os/proc.go:49 +0x2f
main.main()
        github.com/zeromq/goczmq/_test/_testmain.go:58 +0x1ea

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1
rax     0x62ee756e
rbx     0x697bc8a0
rcx     0x22f2f0
rdx     0xb0
rdi     0xa470b0
rsi     0x7fefe193fc0
rbp     0x77572f80
rsp     0x22f900
r8      0x0
r9      0x0
r10     0x0
r11     0x22f940
r12     0x22fb10
r13     0x6fb1da38
r14     0x77657be0
r15     0x77652670
rip     0x7fefd7d940d
rflags  0x7fe00000202
cs      0x33
fs      0x53
gs      0x2b
exit status 2
FAIL    github.com/zeromq/goczmq        0.684s
```

**Comment by vrecan** [comment]
This might be a lib issue on my end I am going to create a clean env to see if I can recreate this

**Comment by PSG-Luna** [comment]
It looks like we aren't correctly initializing czmq ? I thought we had an
init statement somewhere to do this

**Comment by taotetek** [comment]
The init is here -
https://github.com/zeromq/goczmq/blob/3979e4cbfca83e04a8ca3ebe3e6d874b785117c7/sock.go#L39

I don't have a windows environment to test or debug in.  If someone who
develops on windows can solve it we're certainly happy for a pull request!

Cheers,
Brian

**Comment by taotetek** [comment]
Closing this for now, as I don't do any work on windows and have had no takers on help. Feel free to request a re-open if you want to work on it.
