### ISSUE TITLE
Poller.Wait() crashes if called after Poller.Destroy()

### ISSUE THREAD

**Issue by jordansissel** [zeromq/goczmq#145]
I found that Poller.Wait() will cause a panic (segfault) if invoked after Poller.Destroy().

Here's some sample code using goroutines (where I would close a Poller in a different goroutine):

```go
package main

import (
  czmq "github.com/zeromq/goczmq"
  "log"
  "os"
  "time"
)

func main() {
  log.SetOutput(os.Stdout)
  sock, _ := czmq.NewRep("inproc://foo")
  poller, _ := czmq.NewPoller(sock)

  go func() { 
    time.Sleep(500 * time.Millisecond)
    log.Printf("Destroying sock now\n")
    sock.Destroy()

    time.Sleep(500 * time.Millisecond)
    log.Printf("Destroying poller now\n")
    poller.Destroy() 
  }() 
  log.Printf("poller.Wait(...)\n")
  poller.Wait(3000)
  log.Printf("poller.Wait(...)\n")
  poller.Wait(3000)
}
```

Here's a single-goroutine example:

```go
  package main
  
  import (
    czmq "github.com/zeromq/goczmq"
    "log"
    "os"
  )
  
  func main() {
    log.SetOutput(os.Stdout)
    sock, _ := czmq.NewRep("inproc://foo")
    poller, _ := czmq.NewPoller(sock)
  
    log.Printf("poller.Wait(...)\n")
    poller.Wait(3000)
    log.Printf("poller.Destroy()\n")
    poller.Destroy() 
    log.Printf("poller.Wait(...)\n")
    poller.Wait(3000)
  }
```

The panic output looks like this:

```
2015/07/19 15:09:01 poller.Wait(...)
2015/07/19 15:09:04 poller.Destroy()
2015/07/19 15:09:04 poller.Wait(...)
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x23 pc=0x7f0947776e0e]

runtime stack:
runtime.gothrow(0x51df70, 0x2a)
        /usr/lib/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/lib/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x406480, 0xc208083e68, 0xc200000000)
        /usr/lib/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208083e48 sp=0xc208083e20
github.com/zeromq/goczmq._Cfunc_zpoller_wait(0x0, 0xbb8, 0x0)
        github.com/zeromq/goczmq/_obj/_cgo_gotypes.go:332 +0x44 fp=0xc208083e68 sp=0xc208083e48
github.com/zeromq/goczmq.(*Poller).Wait(0xc208020060, 0xbb8, 0x0)
        /home/jls/projects/go/src/github.com/zeromq/goczmq/poller.go:87 +0x373 fp=0xc208083f28 sp=0xc208083e68
main.main()
        /home/jls/projects/experiments/go/zmq2.go:19 +0x1b4 fp=0xc208083f98 sp=0xc208083f28
runtime.main()
        /usr/lib/go/src/runtime/proc.go:63 +0xf3 fp=0xc208083fe0 sp=0xc208083f98
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208083fe8 sp=0xc208083fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by taotetek** [comment]
@jordansissel Thanks for the bug report, and for the code to reproduce the case!  I'll see if I can set aside a little time for a patch for this tomorrow.

**Comment by jordansissel** [comment]
@taotetek I found the goczmq code super easy to understand, so I proposed a little patch in #146 (with tests, yay!). Do let me know if you want anything else added!
