### ISSUE TITLE
Thread Safe Channels Example Fails

### ISSUE THREAD

**Issue by rgbkrk** [zeromq/goczmq#154]
```
$ go run thread_safe_channel.go
2015/08/16 09:57:27 router created and bound
2015/08/16 09:57:27 dealer created and connected
Assertion failed: (!s_process_ctx), function zsys_init, file src/zsys.c, line 179.
SIGABRT: abort
PC=0x7fff9510f286
signal arrived during cgo execution

goroutine 6 [syscall, locked to thread]:
runtime.cgocall_errno(0x4001850, 0xc208059cf0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/cgocall.go:130 +0xf5 fp=0xc208059cd0 sp=0xc208059ca8
github.com/zeromq/goczmq._Cfunc_zsock_new_checked(0x0, 0x5000200, 0xdb, 0x0)
	github.com/zeromq/goczmq/_obj/_cgo_gotypes.go:479 +0x44 fp=0xc208059cf0 sp=0xc208059cd0
github.com/zeromq/goczmq.NewSock(0x0, 0xc20803a300)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/sock.go:81 +0x189 fp=0xc208059d68 sp=0xc208059cf0
github.com/zeromq/goczmq.NewPair(0xc20803a300, 0x29, 0xc208059e98, 0x0, 0x0)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/sock.go:219 +0x39 fp=0xc208059da8 sp=0xc208059d68
github.com/zeromq/goczmq.(*Channeler).actor(0xc208010070, 0xc2080500c0)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/channeler.go:35 +0x141 fp=0xc208059fd0 sp=0xc208059da8
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208059fd8 sp=0xc208059fd0
created by github.com/zeromq/goczmq.newChanneler
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/channeler.go:186 +0x45b

goroutine 1 [chan send]:
main.main()
	/Users/kyle6475/code/src/github.com/rgbkrk/junkie/thread_safe_channel.go:25 +0x2fe

goroutine 5 [syscall, locked to thread]:
github.com/zeromq/goczmq._Cfunc_zsock_attach(0x5000470, 0x54003c0, 0x5400300, 0x0)
	github.com/zeromq/goczmq/_obj/_cgo_gotypes.go:347 +0x43
github.com/zeromq/goczmq.(*Sock).Attach(0xc20805bfa8, 0x2, 0x2, 0x4016062, 0xc20805bf30, 0x0)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/sock.go:132 +0x68
created by github.com/zeromq/goczmq.newChanneler
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/channeler.go:185 +0x437

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [runnable, locked to thread]:
github.com/zeromq/goczmq._Cfunc_zsock_attach(0x5200040, 0x52000e0, 0x5200000, 0x0)
	github.com/zeromq/goczmq/_obj/_cgo_gotypes.go:347 +0x43
github.com/zeromq/goczmq.(*Sock).Attach(0xc208034300, 0xc20803a2d0, 0x21, 0x0, 0x0, 0x0)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/sock.go:132 +0x68
github.com/zeromq/goczmq.NewPush(0x40f94b0, 0x3, 0xc208054ed8, 0x1, 0x1)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/sock.go:185 +0x65
github.com/zeromq/goczmq.(*Channeler).channeler(0xc2080100e0, 0xc208050180, 0xc2080501e0)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/channeler.go:127 +0x4b
created by github.com/zeromq/goczmq.newChanneler
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/channeler.go:185 +0x437
2015/08/16 09:57:27 dealer sent 'Hello'

goroutine 8 [syscall, locked to thread]:
github.com/zeromq/goczmq._Cfunc_zframe_recv(0x52003d0, 0x0)
	github.com/zeromq/goczmq/_obj/_cgo_gotypes.go:305 +0x44
github.com/zeromq/goczmq.(*Sock).RecvFrame(0x0, 0x404307a, 0x5200860, 0xffffffff, 0x0, 0x1, 0x1)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/sock.go:268 +0x72
created by github.com/zeromq/goczmq.newChanneler
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/channeler.go:186 +0x45b

rax     0x0
rbx     0x6
rcx     0x7fff5fbfea58
rdx     0x0
rdi     0x30b
rsi     0x6
rbp     0x7fff5fbfea80
rsp     0x7fff5fbfea58
r8      0x0
r9      0xb3
r10     0x8000000
r11     0x206
r12     0x422303c
r13     0x4370000
r14     0x7fff7846b300
r15     0x4222f8b
rip     0x7fff9510f286
rflags  0x206
cs      0x7
fs      0x0
gs      0x0
exit status 2
```

**Comment by rgbkrk** [comment]
Same thing with `go test` in this repo:

```
$ go test
# github.com/zeromq/goczmq
./cert.go:6:99: warning: control reaches end of non-void function [-Wreturn-type]
Assertion failed: (rc == 0 || zmq_errno () == ETERM), function zsocket_set_curve_secretkey_bin, file src/zsockopt.c, line 482.
SIGABRT: abort
PC=0x7fff9510f286
signal arrived during cgo execution

goroutine 7 [syscall, locked to thread]:
runtime.cgocall_errno(0x4001790, 0xc208018e20, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/cgocall.go:130 +0xf5 fp=0xc208018e00 sp=0xc208018dd8
github.com/zeromq/goczmq._Cfunc_zsocket_set_curve_secretkey_bin(0x480c800, 0x4506290)
	github.com/zeromq/goczmq/_test/_obj_test/_cgo_gotypes.go:923 +0x45 fp=0xc208018e20 sp=0xc208018e00
github.com/zeromq/goczmq.(*Cert).Apply(0xc20804e098, 0xc20804d840)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/cert.go:76 +0x5e fp=0xc208018e40 sp=0xc208018e20
github.com/zeromq/goczmq.TestAuthCurveAllow(0xc20806e120)
	/Users/kyle6475/code/src/github.com/zeromq/goczmq/auth_test.go:224 +0x23c fp=0xc208018f78 sp=0xc208018e40
testing.tRunner(0xc20806e120, 0x42c0d10)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:447 +0xbf fp=0xc208018fd0 sp=0xc208018f78
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fd8 sp=0xc208018fd0
created by testing.RunTests
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x4222f08, 0x42c0ce0, 0x47, 0x47, 0x42d5901)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208050460, 0x42bf800)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:485 +0x6c
main.main()
	github.com/zeromq/goczmq/_test/_testmain.go:232 +0x1d5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

rax     0x0
rbx     0x6
rcx     0x7fff5fbfeb18
rdx     0x0
rdi     0x30b
rsi     0x6
rbp     0x7fff5fbfeb40
rsp     0x7fff5fbfeb18
r8      0x0
r9      0x1e2
r10     0x8000000
r11     0x206
r12     0x43652eb
r13     0x44b4000
r14     0x7fff7846b300
r15     0x43681f0
rip     0x7fff9510f286
rflags  0x206
cs      0x7
fs      0x0
gs      0x0
exit status 2
FAIL	github.com/zeromq/goczmq	0.240s
```

**Comment by taotetek** [comment]
@rgbkrk - thanks for the issue report!  Looking at the output of your failure when running go test in the repo, it looks to me like you are using a CZMQ that is compiled without libsodium support for encryption ( see:  "Assertion failed: (rc == 0 || zmq_errno () == ETERM), function zsocket_set_curve_secretkey_bin, file src/zsockopt.c, line 482." )

Tests are passing locally and in travis-ci for me.
```
 go test
PASS
ok  	github.com/zeromq/goczmq	0.653s
```

The channeler example from the README is also working locally:
```
 go run channel_example.go 
2015/08/16 15:06:26 router created and bound
2015/08/16 15:06:26 dealer created and connected
2015/08/16 15:06:26 dealer sent 'Hello'
2015/08/16 15:06:26 router received 'Hello' from '[0 121 82 116 107]'
2015/08/16 15:06:26 router sent 'World'
2015/08/16 15:06:26 dealer received 'World'
```

Could you let me know the versions of libzmq and czmq you are using, and how you installed / compiled them?

Thanks!

**Comment by rgbkrk** [comment]
Thanks @taotetek, that made it immediately clear! I'm on a new Mac with a fresh homebrew and zmq installation. The recipe on homebrew doesn't install with libsodium by default, requiring the `--with-libsodium` option.

Reinstalling and running tests was then flawless:

```
$ brew uninstall zmq
Uninstalling /usr/local/Cellar/zeromq/4.1.2... (63 files, 3.3M)
$ brew install zmq --with-libsodium
==> Downloading http://download.zeromq.org/zeromq-4.1.2.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/zeromq/4.1.2 --with-libsodium
==> make
==> make install
🍺  /usr/local/Cellar/zeromq/4.1.2: 63 files, 3.3M, built in 49 seconds
$ go test
# github.com/zeromq/goczmq
./cert.go:6:99: warning: control reaches end of non-void function [-Wreturn-type]
PASS
ok  	github.com/zeromq/goczmq	0.684s
```

**Comment by rgbkrk** [comment]
While I'm at it, I'll see about making the libsodium option enabled by default on homebrew. What do you think?

**Comment by taotetek** [comment]
@rgbkrk Glad I could help!  I think having sodium enabled by default makes sense!

**Comment by rgbkrk** [comment]
Care to chime in to the question on https://github.com/Homebrew/homebrew/issues/43010 asking

> Are there any downsides to having that on by default?
