### ISSUE TITLE
runtime: found in object at *(0xc82121bdf8+0x20)

### ISSUE THREAD

**Issue by demyan** [zeromq/goczmq#180]
- libzmq 4.1.3
- libczmq 3.0.2
- go 1.5/1.5.1 and built from master (6f77278)

I observe this crash periodically (similar to https://github.com/pebbe/zmq2/issues/3 ):

```
runtime: pointer 0xc821843680 to unused region of spanidx=0xc21 span.start=0xc8210aa000 span.li
mit=0xc8210ac000 span.state=0
runtime: found in object at *(0xc82121bdf8+0x20)
object=0xc82121bdf8 k=0x641090d s.start*_PageSize=0xc82121a000 s.limit=0xc82122ff80 s.sizeclass
=15 s.elemsize=224
 *(object+0) = 0xc8206c3c20
 *(object+8) = 0xc8206c3f20
 *(object+16) = 0xc8203cce40
 *(object+24) = 0xc8206c2d20
 *(object+32) = 0xc821843680 <==
 *(object+40) = 0x20d
 *(object+48) = 0x7fded2ce0598
 *(object+56) = 0xc8201b9da0
 *(object+64) = 0x240
 *(object+72) = 0x2
 *(object+80) = 0x3
 *(object+88) = 0x2
 *(object+96) = 0xc8203d8830
 *(object+104) = 0xc820845260
 *(object+112) = 0xc821843680
 *(object+120) = 0x20d
 *(object+128) = 0x20d
 *(object+136) = 0xc820168480
 *(object+144) = 0x20d
 *(object+152) = 0xc8205f92c0
 *(object+160) = 0x3
 *(object+168) = 0x3
 *(object+176) = 0x30003
 *(object+184) = 0xc82121bf68
 *(object+192) = 0xc82121bf50
 *(object+200) = 0xc82121be68
 *(object+208) = 0xc8206c3c20
 *(object+216) = 0x4a1c17


fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
runtime stack:
runtime.throw(0xc84600, 0x3e)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.heapBitsForObject(0xc821843680, 0xc82121bdf8, 0x20, 0x0, 0x0, 0x0, 0x7fded2c64770)
        /usr/local/go/src/runtime/mbitmap.go:231 +0x412
runtime.scanblock(0xc82121bdf8, 0x178, 0xcb6a68, 0xc820021c20)
        /usr/local/go/src/runtime/mgcmark.go:698 +0xfb
runtime.scanframeworker(0x7fdeafffeba8, 0x0, 0xc820021c20)
        /usr/local/go/src/runtime/mgcmark.go:521 +0x14c
runtime.scanstack.func1(0x7fdeafffeba8, 0x0, 0x7fded2d000000101)
        /usr/local/go/src/runtime/mgcmark.go:440 +0x65
runtime.gentraceback(0x435074, 0xc82121bc38, 0x0, 0xc8202f8000, 0x0, 0x0, 0x7fffffff, 0x7fdeaff
fecc8, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:338 +0xc77
runtime.scanstack(0xc8202f8000)
        /usr/local/go/src/runtime/mgcmark.go:463 +0x38e
runtime.scang(0xc8202f8000)
        /usr/local/go/src/runtime/proc1.go:422 +0xf3
runtime.markroot(0xc820018060, 0x7fde000000ad)
        /usr/local/go/src/runtime/mgcmark.go:110 +0x1da
runtime.parfordo(0xc820018060)
        /usr/local/go/src/runtime/parfor.go:95 +0x12a
runtime.gcscan_m()
        /usr/local/go/src/runtime/mgcmark.go:36 +0xc9
runtime.gc.func2()
        /usr/local/go/src/runtime/mgc.go:1046 +0xe2
runtime.systemstack(0xc82001e000)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674
goroutine 526 [garbage collection scan]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820413c98 sp=0xc820413c90
runtime.gc(0x0)
        /usr/local/go/src/runtime/mgc.go:1055 +0x1e3 fp=0xc820413f90 sp=0xc820413c98
runtime.backgroundgc()
        /usr/local/go/src/runtime/mgc.go:937 +0x3d fp=0xc820413fc0 sp=0xc820413f90
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1805 +0x1 fp=0xc820413fc8 sp=0xc820413fc0
created by runtime.startGC
        /usr/local/go/src/runtime/mgc.go:910 +0x186
...
```

The only Cgo calls I see in stack are:
```
...
goroutine 214 [runnable, locked to thread]:
github.com/zeromq/goczmq._Cfunc_zframe_send(0xc8201fd4a8, 0x7fdec4004160, 0x7fde00000000, 0xc80
0000000)
        github.com/zeromq/goczmq/_obj/_cgo_gotypes.go:554 +0x39
github.com/zeromq/goczmq.(*Sock).SendFrame(0xc8202f3540, 0xc821bd3680, 0x20d, 0x240, 0x0, 0x0,
0x0)
        /home/demyan/repos/gorepos/src/github.com/zeromq/goczmq/sock.go:249 +0x16d
github.com/zeromq/goczmq.(*Sock).SendMessage(0xc8202f3540, 0xc82008ba90, 0x3, 0x3, 0x0, 0x0)
        /home/demyan/repos/gorepos/src/github.com/zeromq/goczmq/sock.go:299 +0xfc
github.com/demyan/mm/kernel.(*Worker).ZmqPushLoopRun(0xc820206300)
        /home/demyan/repos/gorepos/src/github.com/demyan/mm/kernel/worker.go:278 +0x12c
created by github.com/demyan/mm/kernel.(*Worker).Run
        /home/demyan/repos/gorepos/src/github.com/demyan/mm/kernel/worker.go:120 +0x4f
goroutine 215 [syscall, locked to thread]:
github.com/zeromq/goczmq._Cfunc_zpoller_wait(0x7fdec4004940, 0x1f4, 0x0)
        github.com/zeromq/goczmq/_obj/_cgo_gotypes.go:605 +0x3a
github.com/zeromq/goczmq.(*Poller).Wait(0xc8203d4160, 0x1f4, 0xc820c22f0f)
        /home/demyan/repos/gorepos/src/github.com/zeromq/goczmq/poller.go:87 +0x83
github.com/demyan/mm/kernel.(*Worker).ZmqPullLoopRun(0xc820206300)
        /home/demyan/repos/gorepos/src/github.com/demyan/mm/kernel/worker.go:306 +0x1de
created by github.com/demyan/mm/kernel.(*Worker).Run
        /home/demyan/repos/gorepos/src/github.com/demyan/mm/kernel/worker.go:121 +0x74
...
```

**Comment by taotetek** [comment]
@demyan Thanks for the issue report!  Do you have a minimal test case that can reliably reproduce this error?

**Comment by demyan** [comment]
Unfortunately I can reproduced only with our complicated codebase and it fails periodically. I tried to switch to https://github.com/pebbe/zmq4 but had similar panics. Maybe it has same approach of using unsafe in Cgo polling/sending calls.  https://github.com/golang/go/issues/12138

**Comment by taotetek** [comment]
@demyan the polling code is pretty thoroughly tested with both unit tests and benchmark tests.  This of course does not rule out edge cases.  Without a reliable way to reproduce the issue on my end it's very difficult to look into.  I'm going to close the issue as I can't verify it, but I will keep it in mind and if I do manage to stumble on a reliable way to reproduce it, I'll let you know.  If you end up being able to provide a test case for it also please let me know.

Thanks!
