### ISSUE TITLE
SIGABRT on newReq() in simultaneous goroutines

### ISSUE THREAD

**Issue by bjubes** [zeromq/goczmq#304]
I get an inconsistent, occasional SIGABRT on calling newReq(). The program opens many request lines, so my initial guess is that calling newReq from many goroutines at once is causing the crash? Here is the panic:
```
web_controller: src/zsys.c:219: zsys_init: Assertion `!s_process_ctx' failed.
SIGABRT: abort
PC=0x7f1fcf38b03b m=6 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f1fcf38b03b
stack: frame={sp:0x7f1fa5c57770, fp:0x0} stack=[0x7f1fa5457f30,0x7f1fa5c57b30)
0x00007f1fa5c57670:  0x00000000005e5d72 <gopkg.in/zeromq/goczmq%2ev4.NewReq+0x0000000000000052>  0x0000000000000000 
0x00007f1fa5c57680:  0x0000000000415d28 <runtime.mallocgc+0x00000000000004e8>  0x0000007800003f5f 
0x00007f1fa5c57690:  0x0000000000000000  0x0000000000000070 
0x00007f1fa5c576a0:  0xffffffffa5c57790  0x0000000000412740 <runtime.Caller+0x0000000000000000> 
0x00007f1fa5c576b0:  0x0000000000000064  0x0000000000000007 
0x00007f1fa5c576c0:  0x00007f1fa5c57740  0x0000000000459aad <runtime.funcspdelta+0x000000000000004d> 
0x00007f1fa5c576d0:  0x0000000000000001  0x0000003100000007 
0x00007f1fa5c576e0:  0x0000000000000000  0x00007f1f94000020 
0x00007f1fa5c576f0:  0x00007f1f94000db0  0x000000000000004f 
0x00007f1fa5c57700:  0x000000000000004f  0x00007f1f94000da0 
0x00007f1fa5c57710:  0x0000000000000070  0x00007f1fcf3e3186 
0x00007f1fa5c57720:  0x3931321fa5c57780  0xfceb9bdaa1ab0300 
0x00007f1fa5c57730:  0x00007f1f94000db0  0x00007f1fa5c579d0 
0x00007f1fa5c57740:  0x000000000000004e  0x000000000000004e 
0x00007f1fa5c57750:  0x000000000000004f  0x00007f1f94000db0 
0x00007f1fa5c57760:  0x00007f1fa5c57780  0x00007f1fcf3d3c39 
0x00007f1fa5c57770: <0x0000000000000000  0x00007f1fcf3e2700 
0x00007f1fa5c57780:  0x00000000fbad8000  0x00007f1f94000db0 
0x00007f1fa5c57790:  0x00007f1f94000db0  0x00007f1f94000db0 
0x00007f1fa5c577a0:  0x00007f1f94000db0  0x00007f1f94000dfe 
0x00007f1fa5c577b0:  0x00007f1f94000e14  0x00007f1f94000db0 
0x00007f1fa5c577c0:  0x00007f1f94000e14  0x0000000000000000 
0x00007f1fa5c577d0:  0x0000000000000000  0x0000000000000000 
0x00007f1fa5c577e0:  0x0000000000000000  0x0000000000000000 
0x00007f1fa5c577f0:  0xfffffffe7fffffff  0xffffffffffffffff 
0x00007f1fa5c57800:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57810:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57820:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57830:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57840:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57850:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57860:  0xffffffffffffffff  0xffffffffffffffff 
runtime: unknown pc 0x7f1fcf38b03b
stack: frame={sp:0x7f1fa5c57770, fp:0x0} stack=[0x7f1fa5457f30,0x7f1fa5c57b30)
0x00007f1fa5c57670:  0x00000000005e5d72 <gopkg.in/zeromq/goczmq%2ev4.NewReq+0x0000000000000052>  0x0000000000000000 
0x00007f1fa5c57680:  0x0000000000415d28 <runtime.mallocgc+0x00000000000004e8>  0x0000007800003f5f 
0x00007f1fa5c57690:  0x0000000000000000  0x0000000000000070 
0x00007f1fa5c576a0:  0xffffffffa5c57790  0x0000000000412740 <runtime.Caller+0x0000000000000000> 
0x00007f1fa5c576b0:  0x0000000000000064  0x0000000000000007 
0x00007f1fa5c576c0:  0x00007f1fa5c57740  0x0000000000459aad <runtime.funcspdelta+0x000000000000004d> 
0x00007f1fa5c576d0:  0x0000000000000001  0x0000003100000007 
0x00007f1fa5c576e0:  0x0000000000000000  0x00007f1f94000020 
0x00007f1fa5c576f0:  0x00007f1f94000db0  0x000000000000004f 
0x00007f1fa5c57700:  0x000000000000004f  0x00007f1f94000da0 
0x00007f1fa5c57710:  0x0000000000000070  0x00007f1fcf3e3186 
0x00007f1fa5c57720:  0x3931321fa5c57780  0xfceb9bdaa1ab0300 
0x00007f1fa5c57730:  0x00007f1f94000db0  0x00007f1fa5c579d0 
0x00007f1fa5c57740:  0x000000000000004e  0x000000000000004e 
0x00007f1fa5c57750:  0x000000000000004f  0x00007f1f94000db0 
0x00007f1fa5c57760:  0x00007f1fa5c57780  0x00007f1fcf3d3c39 
0x00007f1fa5c57770: <0x0000000000000000  0x00007f1fcf3e2700 
0x00007f1fa5c57780:  0x00000000fbad8000  0x00007f1f94000db0 
0x00007f1fa5c57790:  0x00007f1f94000db0  0x00007f1f94000db0 
0x00007f1fa5c577a0:  0x00007f1f94000db0  0x00007f1f94000dfe 
0x00007f1fa5c577b0:  0x00007f1f94000e14  0x00007f1f94000db0 
0x00007f1fa5c577c0:  0x00007f1f94000e14  0x0000000000000000 
0x00007f1fa5c577d0:  0x0000000000000000  0x0000000000000000 
0x00007f1fa5c577e0:  0x0000000000000000  0x0000000000000000 
0x00007f1fa5c577f0:  0xfffffffe7fffffff  0xffffffffffffffff 
0x00007f1fa5c57800:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57810:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57820:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57830:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57840:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57850:  0xffffffffffffffff  0xffffffffffffffff 
0x00007f1fa5c57860:  0xffffffffffffffff  0xffffffffffffffff 

goroutine 10 [syscall]:
runtime.cgocall(0x7664f0, 0xc00020ebf0)
        /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00020ebc8 sp=0xc00020eb90 pc=0x40c59c
gopkg.in/zeromq/goczmq%2ev4._Cfunc_zsock_new_checked(0x3, 0x7f1f94000ce0, 0xbd)
        _cgo_gotypes.go:1086 +0x4d fp=0xc00020ebf0 sp=0xc00020ebc8 pc=0x5e53cd
gopkg.in/zeromq/goczmq%2ev4.NewSock(0x3)
        /opt/go/pkg/mod/gopkg.in/zeromq/goczmq.v4@v4.1.0/sock.go:85 +0x196 fp=0xc00020ec68 sp=0xc00020ebf0 pc=0x5e57d6
gopkg.in/zeromq/goczmq%2ev4.NewReq({0xc0002a8000, 0x15})
        /opt/go/pkg/mod/gopkg.in/zeromq/goczmq.v4@v4.1.0/sock.go:189 +0x28 fp=0xc00020eca0 sp=0xc00020ec68 pc=0x5e5d48
main.bindReq({0x82a945, 0xa}, {0x82c068, 0xe})
        /opt/app/req.go:45 +0x125 fp=0xc00020ed58 sp=0xc00020eca0 pc=0x763a05
...
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00020efe8 sp=0xc00020efe0 pc=0x46bfe1
created by main.main
        /opt/app/main.go:36 +0x65


goroutine 11 [runnable]:
gopkg.in/zeromq/goczmq%2ev4.(*Sock).Attach.func1(0x7f1f98006230)
        /opt/go/pkg/mod/gopkg.in/zeromq/goczmq.v4@v4.1.0/sock.go:149 +0x2c
gopkg.in/zeromq/goczmq%2ev4.(*Sock).Attach(0x3, {0xc000220000, 0x14}, 0x0)
        /opt/go/pkg/mod/gopkg.in/zeromq/goczmq.v4@v4.1.0/sock.go:149 +0x53
gopkg.in/zeromq/goczmq%2ev4.NewReq({0xc000220000, 0x14})
        /opt/go/pkg/mod/gopkg.in/zeromq/goczmq.v4@v4.1.0/sock.go:190 +0x3e
main.bindReq({0x82cad7, 0x10}, {0x82ea16, 0x14})
        /opt/app/req.go:45 +0x125
...
created by main.main
        /opt/app/main.go:37 +0x73

goroutine 12 [runnable]:
gopkg.in/zeromq/goczmq%2ev4._Cfunc_zsock_new_checked(0x3, 0xc2dac0, 0xbd)
        _cgo_gotypes.go:1086 +0x4d
gopkg.in/zeromq/goczmq%2ev4.NewSock(0x3)
        /opt/go/pkg/mod/gopkg.in/zeromq/goczmq.v4@v4.1.0/sock.go:85 +0x196
gopkg.in/zeromq/goczmq%2ev4.NewReq({0xc000028300, 0x14})
        /opt/go/pkg/mod/gopkg.in/zeromq/goczmq.v4@v4.1.0/sock.go:189 +0x28
main.bindReq({0x82f973, 0x16}, {0x8318f4, 0x1a})
        /opt/app/req.go:45 +0x125
...
created by main.main
        /opt/app/main.go:38 +0x85

rax    0x0
rbx    0x7f1fa5c58700
rcx    0x7f1fcf38b03b
rdx    0x0
rdi    0x2
rsi    0x7f1fa5c57770
rbp    0x7f1fcf500588
rsp    0x7f1fa5c57770
r8     0x0
r9     0x7f1fa5c57770
r10    0x8
r11    0x246
r12    0x7f1fcf5b9655
r13    0xdb
r14    0x7f1fcf5b984f
r15    0x7f1fa7e02100
rip    0x7f1fcf38b03b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by paddor** [comment]
This might be of interest to you: [OMQ.go](https://github.com/paddor/omq.rs/tree/main/bindings/go). It serializes native socket access and supports goroutine-safe calls.
