### ISSUE TITLE
Possible Issue w/ latest ZeroMQ and CZMQ Release Candidates

### ISSUE THREAD

**Issue by taotetek** [zeromq/goczmq#79]
brian,

i am using czmq-3.0.0-rc1 and zeromq-4.1.0.-rc1

the result of a make build is
> find . -name \*.go -type f -exec gofmt -w {} \;
> go get -t -v ./...
> go test -v .
> === RUN TestAuthIPAllow
> I: 15-01-17 17:20:09 zauth: API command=ALLOW
> I: 15-01-17 17:20:09 zauth: - whitelisting ipaddress=127.0.0.1
> I: 15-01-17 17:20:09 zauth: ZAP request mechanism=NULL ipaddress=127.0.0.1
> I: 15-01-17 17:20:09 zauth: - passed (whitelist) address=127.0.0.1
> I: 15-01-17 17:20:09 zauth: - ZAP reply status_code=200 status_text=OK
> I: 15-01-17 17:20:09 zauth: API command=$TERM
> --- PASS: TestAuthIPAllow (0.00s)
> === RUN TestAuthPlain
> I: 15-01-17 17:20:09 zauth: API command=ALLOW
> I: 15-01-17 17:20:09 zauth: - whitelisting ipaddress=127.0.0.1
> I: 15-01-17 17:20:09 zauth: API command=PLAIN
> I: 15-01-17 17:20:09 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
> I: 15-01-17 17:20:09 zauth: - passed (whitelist) address=127.0.0.1
> I: 15-01-17 17:20:09 zauth: - allowed (PLAIN) username=admin password=Password
> I: 15-01-17 17:20:09 zauth: - ZAP reply status_code=200 status_text=OK
> I: 15-01-17 17:20:09 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
> I: 15-01-17 17:20:09 zauth: - passed (whitelist) address=127.0.0.1
> I: 15-01-17 17:20:09 zauth: - denied (PLAIN) username=admin password=BadPassword
> I: 15-01-17 17:20:09 zauth: - ZAP reply status_code=400 status_text=No access
> I: 15-01-17 17:20:09 zauth: API command=$TERM
> --- PASS: TestAuthPlain (0.20s)
> === RUN TestAuthCurveAllow
> goczmq.test: src/zsockopt.c:482: zsocket_set_curve_secretkey_bin: Assertion `rc == 0 || zmq_errno () == (156384712 + 53)' failed.
> SIGABRT: abort
> PC=0x7f0ce5ba2877
> signal arrived during cgo execution
>
> goroutine 7 [syscall, locked to thread]:
> runtime.cgocall_errno(0x406070, 0xc20801d628, 0x0)
> /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc20801d608 sp=0xc20801d5e0
> github.com/zeromq/goczmq._Cfunc_zsocket_set_curve_secretkey_bin(0x7f0cd800ac90, 0x7f0cd800d010)
> github.com/zeromq/goczmq/_test/_obj_test/_cgo_gotypes.go:883 +0x45 fp=0xc20801d628 sp=0xc20801d608
> github.com/zeromq/goczmq.(*Cert).Apply(0xc20802c088, 0xc20803c540)
> /home/andrew/go/src/github.com/zeromq/goczmq/cert.go:75 +0x5e fp=0xc20801d648 sp=0xc20801d628
> github.com/zeromq/goczmq.TestAuthCurveAllow(0xc208056120)
> /home/andrew/go/src/github.com/zeromq/goczmq/auth_test.go:211 +0x210 fp=0xc20801d778 sp=0xc20801d648
> testing.tRunner(0xc208056120, 0x84e550)
> /usr/local/go/src/testing/testing.go:447 +0xbf fp=0xc20801d7d0 sp=0xc20801d778
> runtime.goexit()
> /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7d8 sp=0xc20801d7d0
> created by testing.RunTests
> /usr/local/go/src/testing/testing.go:555 +0xa8b
>
> goroutine 1 [chan receive]:
> testing.RunTests(0x5d1ed8, 0x84e520, 0x40, 0x40, 0x7b05f8fffe641201)
> /usr/local/go/src/testing/testing.go:556 +0xad6
> testing.(*M).Run(0xc20802e0a0, 0x868fc0)
> /usr/local/go/src/testing/testing.go:485 +0x6c
> main.main()
> github.com/zeromq/goczmq/_test/_testmain.go:178 +0x1d5
>
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
>
> rax     0x0
> rbx     0x7f0ce6831000
> rcx     0xffffffffffffffff
> rdx     0x6
> rdi     0x5be7
> rsi     0x5be9
> rbp     0x7f0ce5ce8b48
> rsp     0x7f0ce493dc28
> r8      0x1
> r9      0xfefefefefeff092d
> r10     0x8
> r11     0x206
> r12     0x7f0ce640df40
> r13     0x7f0ce6418760
> r14     0x2
> r15     0xc20803c360
> rip     0x7f0ce5ba2877
> rflags  0x206
> cs      0x33
> fs      0x0
> gs      0x0
> exit status 2
> FAIL	github.com/zeromq/goczmq	0.212s
> make: *** [test] Error 1

is that enough info for you?

**Comment by taotetek** [comment]
Was a problem with a libzmq built without libsodium.
